### ISSUE TITLE
Deploy not working

### ISSUE THREAD

**Issue by evoactivity** [mydea/ember-prerender#116]
Running from the cli works.
Normal ember build works.
The deploy pipeline without this plugin works (just a using the normal deploy build step)

When adding the deploy plugin I receive the following errors.

```
Building into /private/var/folders/rw/zh799lvx7lzb46z1mh_r851m0000gn/T/embroider/4252b2
Error: @ember/test-helpers/-internal/build-registry.js: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  },
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  }
]Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  },
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  }
]
    at assertNoDuplicates (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:183:13)
    at createDescriptors (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:107:3)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at /Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:65:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:251:28)
    at Function.sync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:89:14)
    at sync (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/gensync-utils/async.js:62:25)
    at sync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:182:19)
    at onFirstPause (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:210:24)
    at Generator.next (<anonymous>)
    at cachedFunction (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at mergeChainOpts (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-chain.js:350:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-chain.js:317:14)
    at chainWalker.next (<anonymous>)
    at buildRootChain (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-chain.js:57:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/full.js:36:46)
    at loadFullConfig.next (<anonymous>)
    at transform (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/transform.js:20:45)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:251:28)
    at sync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at Object.transform (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/transform.js:36:80)
    at /Users/liam/project/monorepo/node_modules/.pnpm/broccoli-babel-transpiler@7.8.1/node_modules/broccoli-babel-transpiler/lib/worker.js:12:31
    at tryCatcher (/Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
        in /var/folders/rw/zh799lvx7lzb46z1mh_r851m0000gn/T/broccoli-78057ZQxzriYvEoNh/out-024-funnel
        at broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers] (Babel: @ember/test-helpers)
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  },
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  }
]Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  },
  {
    "name": "@embroider/macros cache buster: /Users/liam/project/monorepo/node_modules/.pnpm/@ember+test-helpers@2.9.3_@babel+core@7.22.11_@glint+template@1.1.0_ember-source@4.10.0/node_modules/@ember/test-helpers",
    "alias": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
    "options": {
      "version": "6b4f3cadff3e2d421453f0456708b35c418929b95ddb90f406b9aa559ed3dbc9"
    },
    "dirname": "/Users/liam/project/monorepo/apps/web",
    "ownPass": false,
    "file": {
      "request": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js",
      "resolved": "/Users/liam/project/monorepo/node_modules/.pnpm/@embroider+shared-internals@2.4.0/node_modules/@embroider/shared-internals/src/babel-plugin-cache-busting.js"
    }
  }
]
    at assertNoDuplicates (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:183:13)
    at createDescriptors (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:107:3)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:99:17)
    at createPluginDescriptors.next (<anonymous>)
    at /Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-descriptors.js:65:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:251:28)
    at Function.sync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:89:14)
    at sync (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/gensync-utils/async.js:62:25)
    at sync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:182:19)
    at onFirstPause (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:210:24)
    at Generator.next (<anonymous>)
    at cachedFunction (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/caching.js:52:46)
    at cachedFunction.next (<anonymous>)
    at mergeChainOpts (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-chain.js:350:34)
    at mergeChainOpts.next (<anonymous>)
    at chainWalker (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-chain.js:317:14)
    at chainWalker.next (<anonymous>)
    at buildRootChain (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/config-chain.js:57:36)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/partial.js:72:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/config/full.js:36:46)
    at loadFullConfig.next (<anonymous>)
    at transform (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/transform.js:20:45)
    at transform.next (<anonymous>)
    at evaluateSync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:251:28)
    at sync (/Users/liam/project/monorepo/node_modules/.pnpm/gensync@1.0.0-beta.2/node_modules/gensync/index.js:89:14)
    at stopHiding - secret - don't use this - v1 (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
    at Object.transform (/Users/liam/project/monorepo/node_modules/.pnpm/@babel+core@7.22.11_supports-color@8.1.1/node_modules/@babel/core/lib/transform.js:36:80)
    at /Users/liam/project/monorepo/node_modules/.pnpm/broccoli-babel-transpiler@7.8.1/node_modules/broccoli-babel-transpiler/lib/worker.js:12:31
    at tryCatcher (/Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:498:33)
    at /Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:562:16
    at flush (/Users/liam/project/monorepo/node_modules/.pnpm/rsvp@4.8.5/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
    at /Users/liam/project/monorepo/node_modules/.pnpm/broccoli-babel-transpiler@7.8.1/node_modules/broccoli-babel-transpiler/lib/parallel-api.js:253:17
    at /Users/liam/project/monorepo/node_modules/.pnpm/workerpool@3.1.2/node_modules/workerpool/lib/Promise.js:163:17
    at /Users/liam/project/monorepo/node_modules/.pnpm/workerpool@3.1.2/node_modules/workerpool/lib/Promise.js:69:7
    at Array.forEach (<anonymous>)
    at _resolve (/Users/liam/project/monorepo/node_modules/.pnpm/workerpool@3.1.2/node_modules/workerpool/lib/Promise.js:68:16)
    at Object.resolve (/Users/liam/project/monorepo/node_modules/.pnpm/workerpool@3.1.2/node_modules/workerpool/lib/Promise.js:146:5)
    at Worker.<anonymous> (/Users/liam/project/monorepo/node_modules/.pnpm/workerpool@3.1.2/node_modules/workerpool/lib/WorkerHandler.js:215:25)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)Pipeline aborted
```

**Comment by evoactivity** [comment]
I was using the lightning deploy pack, installing the dependencies separately without the normal deploy build addon seems to have fixed things.
